#!/bin/sh
# the next line restarts using tclsh \
exec tclsh "$0" "$@"
# -*-tcl-*-
source create_map.tcl

# create map
set config "jd_list|jdlist|2|jd|id|TXT|TXT"
create_map::update $config

# read map (change the module/namespace name: bspmap?)
set mapname [lindex [split $config "|"] 1]
set termlist "Biophysics|Emergency Medicine|Genetics|Molecular Biology|Urology"
create_map::setup $mapname

set terms [split $termlist "|"]

puts "terms: $terms"
foreach term $terms {
  set result [create_map::lookup_term $mapname $term]
  puts "term: $term -> $result"
}

create_map::release $mapname

# try using integer data

set config "jd_list|jdlistint|2|jd|id|TXT|INT"
create_map::update $config


# read map (change the module/namespace name: bspmap?)
set mapname [lindex [split $config "|"] 1]
set termlist "Biophysics|Emergency Medicine|Genetics|Molecular Biology|Urology"
create_map::setup $mapname

set terms [split $termlist "|"]

puts "terms: $terms"
foreach term $terms {
  set result [create_map::lookup_term $mapname $term]
  puts "term: $term -> $result"
}

create_map::release $mapname