#!/bin/sh
# the next line restarts using tclsh \
exec tclsh "$0" "$@"
# -*-tcl-*-

set argv { addison -nfile word-signal-lw.9901-12.l -format phrase -ti 1 -ab 1  }
set argc [llength $argv]

source profile.tcl